# Global Configurations
window_width = 1024
window_height = 1024
window_name = "SpaceBound"
fps = 60
speed = 5
bg_path = "./assets/back.png"
player_path = "./assets/player.png"
meteor_path = "./assets/meteors/"
